---
- name: install cfssl
  get_url:
    url: "{{ client_tools.cfssl.bin_url }}"
    dest: /usr/local/bin/cfssl
    mode: '0755'

- name: install cfssl_json
  get_url:
    url: "{{ client_tools.cfssl_json.bin_url }}"
    dest: /usr/local/bin/cfssl_json
    mode: '0755'

- name: install kubectl
  get_url:
    url: "{{ client_tools.kubectl.bin_url }}"
    dest: /usr/local/bin/kubectl
    mode: '0755'
